name: storage_info
description: Get storage info on Android and iOS
version: 1.0.0
repository: https://github.com/Railway-Engineering-Solutions/storage_info

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.storage_info
        pluginClass: StorageInfoPlugin
      ios:
        pluginClass: StorageInfoPlugin
