name: storage_info
description: Get device storage capacity and available space on Android and iOS.
version: 1.0.0
repository: https://github.com/Railway-Engineering-Solutions/storage_info

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.res.storage_info
        pluginClass: StorageInfoPlugin
      ios:
        pluginClass: StorageInfoPlugin
